---
- hosts: all
  gather_facts: false
  vars:
    mysql_key: /usr/share/keyrings/mysql-apt-config.gpg
    # mysql_repo: http://repo.mysql.com/apt/ubuntu/
    mysql_repo: https://mirrors.tuna.tsinghua.edu.cn/mysql/apt/ubuntu
    mysql_version: mysql-8.4-lts

  handlers:
    - name: restart mysql
      service: name=mysql.service state=restarted

  tasks:
  - name: Add MySQL Key
    ansible.builtin.apt_key:
    #   keyserver: pgp.mit.edu
    #   id: A8D3785C
      url: https://repo.mysql.com/RPM-GPG-KEY-mysql-2025
      keyring: "{{ mysql_key }}"
      state: present

  - name: Add MySQL Repo
    apt_repository:
      repo: "{{ item }}"
      state: present
      filename: mysql
      update_cache: yes
    loop:
      - deb [signed-by={{ mysql_key }}] {{ mysql_repo }} noble {{ mysql_version }}
      - deb [signed-by={{ mysql_key }}] {{ mysql_repo }} noble mysql-tools

  - name: install mysql
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - mysql-server

  # - name: allow remote connect 
  #   replace:
  #     path: /etc/mysql/mysql.conf.d/mysqld.cnf
  #     regexp: '^bind-address'
  #     replace: '# bind-address'
  #   notify: restart mysql